### get_all_blogs
GET http://localhost:3003/api/blogs/

### get_one_blog
GET http://localhost:3003/api/blogs/6617f71372007a66718bbbf6

### create_blog
POST http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1zdGZsb3RmeSIsImlkIjoiNjYzYTg1MDAyZTM1ZmQxODliMzYzZjIwIiwiaWF0IjoxNzE2MjA0MTYzLCJleHAiOjE3MTYyMDc3NjN9.Tz8kiLwwdta9-vbbaJ0jTmWLhsRo4CN4ggZmVXBsTas


{
  "title": "test blog post",
  "author": "test author",
  "url": "/test-blog-post",
  "likes": 2
}

### delete_blog
DELETE http://localhost:3003/api/blogs/6617f71372007a66718bbbf6

### update_blog
PUT http://localhost:3003/api/blogs/6617f71372007a66718bbbf6
content-type: application/json

{
  "title": "Update blog",
  "author": "test author",
  "url": "/test-blog-post",
  "likes": 2
}

### get_unkown
GET http://localhost:3003/x